services:
  web:
    build: .
    ports:
      - "5005:80"
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./.env
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: $DATABASE_USER
      POSTGRES_PASSWORD: $DATABASE_PASSWORD
      POSTGRES_DB: $DATABASE_NAME
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U ${DATABASE_USER} -d ${DATABASE_NAME}'" ]
      interval: 10s
      timeout: 3s
      retries: 3
volumes:
  db_data: