"""empty message

Revision ID: 579ab43a2b59
Revises: 20cb779ccf02
Create Date: 2025-06-22 15:00:30.731403

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '579ab43a2b59'
down_revision = '20cb779ccf02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('short_description', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('short_description')

    # ### end Alembic commands ###
